Single dish page is ready in design
202309-EKTA-JO-FSW/capstone-team-3-2 pull request #25
Opened 2024-03-02 14:07 UTC by Wajd-AlKayyali

2024-03-02 14:09 UTC, Wajd-AlKayyali commented on client/src/pages/products/[id].jsx
@mattshal1 
I would highly appreciate you use the same array in this pull request in your BE work.

2024-03-03 15:57 UTC, Sanad-Alshobaki commented on client/src/app/components/Test.jsx
why did you change the localhost??
keep it 3001/test

2024-03-03 15:59 UTC, Sanad-Alshobaki requested changes
reset the localhost on the test.js file
it belongs to the backend docker mongoDB

2024-03-15 11:48 UTC, Wajd-AlKayyali commented
fixed now

2024-03-20 02:06 UTC, Sanad-Alshobaki approved these changes

2024-03-20 02:06 UTC, merged